import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{readFileSync,writeFileSync,existsSync}from'node:fs';import path from'node:path';
const root=process.cwd(),fixture=JSON.parse(readFileSync('.test-data/portal-preview/access.json','utf8')),adb=path.join(root,'.tools/android/platform-tools/adb.exe'),serial=process.env.YY_ANDROID_SERIAL??'emulator-5556',apk=path.join(root,'artifacts/mobile/kr.school.yeoyang.messenger-Signed.apk'),xmlPath=path.join(root,'.test-data/emulator/mobile-ui.xml');
const passed=[],delay=ms=>new Promise(r=>setTimeout(r,ms));function check(name){passed.push(name);console.log('PASS '+name);}
function command(...args){const response=spawnSync(adb,['-s',serial,...args],{encoding:'utf8',windowsHide:true});if(response.status!==0)throw Error('Android command failed: '+response.stderr);return response.stdout;}
const decode=s=>s.replaceAll('&quot;','"').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&');
function dump(){command('shell','uiautomator','dump','/sdcard/yy-mobile-test.xml');command('pull','/sdcard/yy-mobile-test.xml',xmlPath);return[...readFileSync(xmlPath,'utf8').matchAll(/<node\s+([^>]+)>?/g)].map(m=>Object.fromEntries([...m[1].matchAll(/([\w-]+)="([^"]*)"/g)].map(a=>[a[1],decode(a[2])])));}
function tap(node){assert.ok(node,'Visible control missing');const b=node.bounds.match(/\d+/g).map(Number);command('shell','input','tap',String(Math.round((b[0]+b[2])/2)),String(Math.round((b[1]+b[3])/2)));}
async function readyNode(predicate){for(let n=0;n<12;n++){const node=dump().find(predicate);if(node&&node.enabled==='true')return node;await delay(300);}throw Error('Control did not become interactive');}
async function click(text,cls){tap(await readyNode(n=>n.text===text&&(!cls||n.class===cls)));await delay(350);}
async function scrollTo(text){for(let n=0;n<6;n++){if(dump().some(x=>x.text===text))return;command('shell','input','swipe','540','1900','540','650','350');await delay(350);}throw Error('Scrollable control missing: '+text);}
async function input(placeholder,value){await click(placeholder,'android.widget.EditText');command('shell','input','text',value);command('shell','input','keyevent','KEYCODE_BACK');await delay(250);}
async function waitText(text){for(let n=0;n<12;n++){const nodes=dump();if(nodes.some(x=>x.text.includes(text)))return nodes;await delay(400);}throw Error('Android screen did not show '+text);}
assert.ok(existsSync(apk));command('install','-r',apk);command('shell','pm','clear','kr.school.yeoyang.messenger');command('shell','monkey','-p','kr.school.yeoyang.messenger','-c','android.intent.category.LAUNCHER','1');await delay(1800);await waitText('우리 학교 소식');check('native Android APK installs and launches without desktop runtime');
await input('학교에서 안내한 서버 주소',fixture.portal.replace('127.0.0.1','10.0.2.2'));await input('아이디',fixture.parent);await input('비밀번호',fixture.password);await click('로그인','android.widget.Button');await waitText('10월 현장체험학습 안내');check('native parent login, approved child choices and announcement list');
command('shell','am','force-stop','kr.school.yeoyang.messenger');command('shell','monkey','-p','kr.school.yeoyang.messenger','-c','android.intent.category.LAUNCHER','1');await delay(900);await waitText('10월 현장체험학습 안내');check('automatic secure session restores after app process restart without storing password');
tap(await readyNode(n=>n.class==='android.widget.Button'&&n.text.includes('10월 현장체험학습 안내')));await delay(600);const detail=await waitText('<svg onload=alert(1)>');assert.ok(detail.some(n=>n.text.includes('참가 여부')));check('native notice detail uses plain text and records read receipt');
command('shell','input','keyevent','KEYCODE_BACK');await delay(500);await click('로그아웃','android.widget.Button');await waitText('우리 학교 소식');assert.ok(!dump().some(n=>n.text.includes('현장체험학습 안내')));check('logout clears private announcement screen');
command('shell','am','force-stop','kr.school.yeoyang.messenger');command('shell','monkey','-p','kr.school.yeoyang.messenger','-c','android.intent.category.LAUNCHER','1');await delay(900);await waitText('우리 학교 소식');await click('저장된 로그인으로 접속','android.widget.Button');await waitText('저장된 로그인이 없습니다');check('logout removes secure stored session; process restart cannot restore it');
await click('학교 소식 · 학생/보호자/교사','android.widget.EditText');await click('교직원 교무실 · 교내망/VPN');await input('학교에서 안내한 서버 주소',fixture.office.replace('127.0.0.1','10.0.2.2'));await input('아이디',fixture.admin);await input('비밀번호',fixture.password);await click('로그인','android.widget.Button');await waitText('교직원 업무 메시지 검증');check('native office mode uses a separate school-only service and account session');
tap(await readyNode(n=>n.class==='android.widget.Button'&&n.text.includes('교직원 업무 메시지 검증')));await delay(600);await waitText('교직원 전용 메시지입니다');check('native teacher message detail reads internal API without exporting private text');command('shell','input','keyevent','KEYCODE_BACK');await delay(600);await click('로그아웃','android.widget.Button');await waitText('우리 학교 소식');
await click('교직원 교무실 · 교내망/VPN','android.widget.EditText');await click('학교 소식 · 학생/보호자/교사');await input('학교에서 안내한 서버 주소',fixture.portal.replace('127.0.0.1','10.0.2.2'));await input('아이디',fixture.teacher);await input('비밀번호',fixture.password);await click('로그인','android.widget.Button');await waitText('새 공지 작성');await click('새 공지 작성','android.widget.Button');await scrollTo('공지 보내기');await click('공지 보내기','android.widget.Button');await waitText('제목·내용·수신 학급을 입력하세요.');assert.ok(dump().some(n=>n.text==='공지 제목 (200자 이내)'&&n.enabled==='true'));check('native teacher compose validation leaves missing fields editable before transmission');
command('shell','input','swipe','540','650','540','1900','350');await delay(350);await input('공지 제목 (200자 이내)','Native_publish_test');await input('공지 내용','Native_public_announcement');tap(await readyNode(n=>n.class==='android.widget.CheckBox'));await scrollTo('공지 보내기');await click('공지 보내기','android.widget.Button');await waitText('수신 대상과 내용을 확인했나요?');await click('발송','android.widget.Button');await waitText('Native_publish_test');check('native teacher publishes to the approved class through the external service');
tap(await readyNode(n=>n.class==='android.widget.Button'&&n.text.includes('Native_publish_test')));await waitText('확인 0 / 2');await scrollTo('공지 회수');await click('공지 회수','android.widget.Button');await waitText('수신자의 공지·첨부 접근을 회수할까요?');await click('회수','android.widget.Button');await waitText('새 공지 작성');await click('로그아웃','android.widget.Button');await waitText('우리 학교 소식');check('native sender receipt display and confirmed withdrawal complete without retaining private screens');
writeFileSync('artifacts/mobile-ui-test-results.json',JSON.stringify({at:new Date().toISOString(),device:serial,passed},null,2));console.log(passed.length+' mobile UI checks passed.');
