// Local UI fixture: random credentials, invented people, no school data. Stop with Ctrl+C.
import {spawn} from 'node:child_process';import{randomUUID}from'node:crypto';import{existsSync,mkdirSync,writeFileSync}from'node:fs';import path from'node:path';import net from'node:net';
const root=process.cwd(),sdk=existsSync('.tools/dotnet/dotnet.exe')?path.join(root,'.tools/dotnet/dotnet.exe'):path.join(process.env.DOTNET_ROOT,'dotnet.exe'),password='Test-'+randomUUID(),key='Bridge-'+randomUUID(),fixture=path.join(root,'.test-data','portal-preview');mkdirSync(fixture,{recursive:true});
async function free(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const port=s.address().port;await new Promise(r=>s.close(r));return'http://127.0.0.1:'+port;}
const portal=await free(),office=await free(),children=[];let logs='';
function start(name,base,env){const child=spawn(sdk,[path.join(root,`src/SchoolMessenger.${name}/bin/Debug/net10.0/SchoolMessenger.${name}.dll`),'--urls',base],{cwd:path.join(root,'src','SchoolMessenger.'+name),windowsHide:true,env:{...process.env,ASPNETCORE_ENVIRONMENT:'Development',Portal__AllowedHosts:'localhost,127.0.0.1,10.0.2.2',...env}});children.push(child);child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);}
const data=path.join(fixture,randomUUID());start('AnnouncementServer',portal,{Portal__DataDirectory:path.join(data,'portal'),Portal__AdminPassword:password,Portal__BridgeKey:key});start('Server',office,{School__DataDirectory:path.join(data,'office'),School__AdminPassword:password,Announcements__Address:portal,Announcements__BridgeKey:key});
async function ready(base){for(let n=0;n<100;n++){try{if((await fetch(base+'/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error(logs);}
class Client{constructor(base){this.base=base;this.cookies=new Map();}async req(route,method='GET',body){const headers={Cookie:[...this.cookies].map(([k,v])=>k+'='+v).join('; ')};if(method!=='GET'){headers['X-CSRF-TOKEN']=this.csrf;headers['Content-Type']='application/json';}const response=await fetch(this.base+'/api/'+route,{method,headers,body:method==='GET'?undefined:JSON.stringify(body??{})});for(const item of response.headers.getSetCookie()){const value=item.split(';')[0],at=value.indexOf('=');this.cookies.set(value.slice(0,at),value.slice(at+1));}const text=await response.text();if(!response.ok)throw Error(route+' '+response.status+' '+text);return text?JSON.parse(text):null;}async login(username){this.csrf=(await this.req('session')).csrfToken;await this.req('login','POST',{username,password,rememberLogin:true});const s=await this.req('session');this.csrf=s.csrfToken;this.user=s.user;return this;}}
async function person(admin,name,role,classId=null,internalUserId=null,classIds=[]){return(await admin.req('admin/people','POST',{name,role,classId,internalUserId,classIds,canBroadcast:false})).id;}
async function claim(admin,id,username){const invite=await admin.req('admin/people/'+id+'/invite','POST'),client=new Client(portal);client.csrf=(await client.req('session')).csrfToken;await client.req('register','POST',{code:invite.code,username,password});return client.login(username);}
try{await Promise.all([ready(portal),ready(office)]);const admin=await new Client(portal).login('admin'),teacherOffice=await new Client(office).login('admin');const c1=(await admin.req('admin/classes','POST',{name:'1학년 1반',grade:1})).id,c2=(await admin.req('admin/classes','POST',{name:'2학년 1반',grade:2})).id;const teacherId=await person(admin,'김여양 선생님','teacher',null,teacherOffice.user.id,[c1]);const student=await person(admin,'가상학생 하나','student',c1),student2=await person(admin,'가상학생 둘','student',c2),parent=await person(admin,'가상보호자','parent');for(const studentId of[student,student2])await admin.req('admin/families','POST',{parentId:parent,studentId});await claim(admin,parent,'testparent');await claim(admin,student,'teststudent');for(let i=0;i<30;i++){if((await teacherOffice.req('external-announcements/setup')).teacherId===teacherId)break;await new Promise(r=>setTimeout(r,250));}const teacherPortal=await claim(admin,teacherId,'testteacher');const notice=await teacherPortal.req('announcements','POST',{clientId:randomUUID().replaceAll('-',''),title:'10월 현장체험학습 안내',body:'학생과 학부모님께 안내드립니다.\n\n10월 16일 현장체험학습을 진행합니다. 참가 여부와 준비물을 확인해 주세요.\n\n<svg onload=alert(1)> 이 문구는 HTML로 실행되지 않습니다.',audience:'both',classIds:[c1],all:false,attachmentIds:[]});await teacherOffice.req('messages','POST',{clientId:randomUUID().replaceAll('-',''),title:'교직원 업무 메시지 검증',body:'교직원 전용 메시지입니다. 외부 공지 서버에는 나타나지 않습니다.',recipientIds:[teacherOffice.user.id],attachmentIds:[]});writeFileSync(path.join(fixture,'access.json'),JSON.stringify({portal,office,password,parent:'testparent',teacher:'testteacher',student:'teststudent',admin:'admin',noticeId:notice.id,teacherId,data}));console.log('Local portal/mobile UI fixture ready.');}catch(e){for(const c of children)c.kill();throw e;}
async function close(){for(const c of children)c.kill();process.exit();}process.on('SIGINT',close);process.on('SIGTERM',close);await new Promise(()=>{});
