// Run against tests/portal-preview.mjs. Use an isolated headless browser, never a personal profile.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.YY_PLAYWRIGHT_MODULE?pathToFileURL(process.env.YY_PLAYWRIGHT_MODULE).href:'playwright');
const fixture=JSON.parse(readFileSync('.test-data/portal-preview/access.json','utf8')),passed=[];
const browser=await chromium.launch({headless:true,channel:process.env.YY_BROWSER_CHANNEL??'msedge'});
const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
function check(name){passed.push(name);console.log('PASS '+name);}
async function login(base,username,office=false){await page.goto(base+(office?'/office/':'/'));await page.locator(office?'#username':'[name="username"]').first().fill(username);await page.locator(office?'#password':'[name="password"]').first().fill(fixture.password);await page.getByRole('button',{name:'로그인',exact:true}).click();await page.getByRole('button',{name:'업데이트 내역',exact:true}).waitFor({state:'visible'});const confirm=page.getByRole('button',{name:'확인',exact:true});if(await confirm.isVisible())await confirm.click();}
try{
 await login(fixture.portal,fixture.parent);await page.locator('#timetable').click();const dialog=page.locator('.school-timetable');await dialog.waitFor({state:'visible'});await dialog.getByLabel('조회 날짜').fill(fixture.timetableDate);await dialog.getByRole('button',{name:'선택한 날짜 보기',exact:true}).click();await dialog.getByText('가상 영어',{exact:false}).waitFor();assert.match(await dialog.innerText(),/변경 전: 가상 수학/);assert.match(await dialog.innerText(),/2교시 · 1학년 1반 · 수업 없음/);check('parent web renders dated replacement, previous lesson and empty period');
 const scopes=await dialog.getByLabel('조회할 시간표').locator('option').allTextContents();assert.deepEqual(scopes,['1학년 1반','2학년 1반']);check('parent web offers only linked child classes');
 await dialog.getByLabel('조회 날짜').fill('2026-10-15');await dialog.getByRole('button',{name:'선택한 날짜 보기',exact:true}).click();await dialog.getByText('기초시간표 적용').waitFor();assert.match(await dialog.innerText(),/가상 국어/);check('web returns to baseline on a date without a daily publication');
 await dialog.getByRole('button',{name:'선택한 주 보기',exact:true}).click();await dialog.getByRole('heading',{name:'2026-10-18',exact:true}).waitFor();assert.equal(await dialog.getByRole('heading',{level:3}).count(),7);check('web weekly view contains Monday through Sunday');
 await dialog.getByLabel('조회 날짜').fill('2026-10-08');await dialog.getByRole('button',{name:'선택한 날짜 보기',exact:true}).click();await dialog.getByText('가상 영어',{exact:false}).waitFor();await page.screenshot({path:'artifacts/timetable-web.png',fullPage:true});await dialog.getByRole('button',{name:'닫기',exact:true}).click();await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});assert.equal(await page.locator('.school-timetable').count(),0);check('web logout removes timetable content from the DOM');
 await login(fixture.portal,fixture.student);await page.locator('#timetable').click();await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByLabel('조회할 시간표').locator('option').count(),1);check('student web is restricted to its assigned class');await dialog.getByRole('button',{name:'닫기',exact:true}).click();await page.locator('#logout').click();
 await login(fixture.portal,fixture.teacher);await page.locator('#timetable').click();await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByLabel('조회할 시간표').inputValue(),'mine');await dialog.getByLabel('조회 날짜').fill(fixture.timetableDate);await dialog.getByRole('button',{name:'선택한 날짜 보기',exact:true}).click();await dialog.getByText('가상 영어',{exact:false}).waitFor();check('teacher web selects its own classes from the linked school identity');await dialog.getByRole('button',{name:'닫기',exact:true}).click();
 await login(fixture.office,fixture.admin,true);await page.locator('#timetable').click();await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByLabel('조회할 시간표').inputValue(),'mine');check('office web exposes timetable beside other teacher tools');
 assert.deepEqual(errors,[]);check('all timetable web flows complete without browser exceptions');writeFileSync('artifacts/timetable-web-checks.json',JSON.stringify({passed,version:'1.0.0'},null,2));
}finally{await context.close();await browser.close();}
