// Synthetic files and accounts only. The school's source XLSX files never enter this fixture.
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import path from 'node:path';
import net from 'node:net';
const root=process.cwd(),sdk=existsSync('.tools/dotnet/dotnet.exe')?path.join(root,'.tools/dotnet/dotnet.exe'):process.env.DOTNET_ROOT?path.join(process.env.DOTNET_ROOT,process.platform==='win32'?'dotnet.exe':'dotnet'):'dotnet';
const data=path.join(root,'.test-data','timetable-'+randomUUID()),password='Test-'+randomUUID(),key='Bridge-'+randomUUID(),id=()=>randomUUID().replaceAll('-','');mkdirSync(data,{recursive:true});
const generated=spawnSync(sdk,['run','--project','tests/TimetableChecks','--no-build','--',path.join(data,'files')],{encoding:'utf8',windowsHide:true});assert.equal(generated.status,0,generated.stdout+generated.stderr);process.stdout.write(generated.stdout);
const pause=ms=>new Promise(r=>setTimeout(r,ms));const passed=[];const check=name=>{passed.push(name);console.log('PASS '+name);};let logs='',p,o;
async function address(){const server=net.createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const result='http://127.0.0.1:'+server.address().port;await new Promise(r=>server.close(r));return result;}
const portal=await address(),office=await address();
function start(name,base,env){const runtime=path.join(data,'runtime-'+name);if(!existsSync(runtime))cpSync(path.join(root,`src/SchoolMessenger.${name}/bin/Debug/net10.0`),runtime,{recursive:true});const child=spawn(sdk,[path.join(runtime,`SchoolMessenger.${name}.dll`),'--urls',base],{cwd:path.join(root,'src','SchoolMessenger.'+name),windowsHide:true,env:{...process.env,ASPNETCORE_ENVIRONMENT:'Development',...env}});child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);return child;}
function startPortal(){p=start('AnnouncementServer',portal,{Portal__DataDirectory:path.join(data,'portal'),Portal__AdminPassword:password,Portal__BridgeKey:key});}
function startOffice(){o=start('Server',office,{School__DataDirectory:path.join(data,'office'),School__AdminPassword:password,Announcements__Address:portal,Announcements__BridgeKey:key});}
async function stop(child){if(child?.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}}
async function wait(action){for(let n=0;n<100;n++){try{const value=await action();if(value)return value;}catch{}await pause(150);}throw Error('Fixture did not converge: '+logs.slice(-1500));}
class Client{
 constructor(base){this.base=base;this.cookies=new Map();}
 async req(route,method='GET',body,expected=200,csrf=true){const headers={Cookie:[...this.cookies].map(([k,v])=>k+'='+v).join('; ')};if(method!=='GET'&&csrf)headers['X-CSRF-TOKEN']=this.csrf;let payload;if(body instanceof FormData)payload=body;else if(method!=='GET'){headers['Content-Type']='application/json';payload=JSON.stringify(body??{});}const response=await fetch(this.base+'/api/'+route,{method,headers,body:payload});for(const item of response.headers.getSetCookie()){const value=item.split(';')[0],at=value.indexOf('=');this.cookies.set(value.slice(0,at),value.slice(at+1));}const text=await response.text();assert.equal(response.status,expected,route+' '+text);return text?JSON.parse(text):null;}
 async login(username='admin'){this.csrf=(await this.req('session')).csrfToken;await this.req('login','POST',{username,password});const session=await this.req('session');this.csrf=session.csrfToken;this.user=session.user;return this;}
}
async function person(admin,name,role,classId=null,internalUserId=null,classIds=[]){return(await admin.req('admin/people','POST',{name,role,classId,internalUserId,classIds,canBroadcast:false})).id;}
async function claim(admin,personId,username){const invite=await admin.req('admin/people/'+personId+'/invite','POST'),client=new Client(portal);client.csrf=(await client.req('session')).csrfToken;await client.req('register','POST',{code:invite.code,username,password});return client.login(username);}
function file(name,kind){const form=new FormData();form.append('kind',kind);form.append('file',new Blob([readFileSync(path.join(data,'files',name))]),name);return form;}
try{
 startPortal();startOffice();await Promise.all([wait(async()=>(await fetch(portal+'/health')).ok),wait(async()=>(await fetch(office+'/health')).ok)]);
 const admin=await new Client(portal).login(),owner=await new Client(office).login();const rooms=[];for(let n=1;n<=6;n++)rooms.push((await admin.req('admin/classes','POST',{name:`1학년 ${n}반`,grade:1})).id);
 for(const [username,name] of [['teachera','가상 교사 A'],['teacherb','가상 교사 B'],['homeroom','가상 담임']])await owner.req('admin/users','POST',{username,name,department:'가상 수업 부서',password,isAdmin:false,canBroadcast:false});
 const a=await new Client(office).login('teachera'),b=await new Client(office).login('teacherb'),home=await new Client(office).login('homeroom');
 const aPortal=await person(admin,'가상 교사 A','teacher',null,a.user.id,[rooms[0]]),bPortal=await person(admin,'가상 교사 B','teacher',null,b.user.id,[rooms[1]]);
 const studentId=await person(admin,'가상 학생','student',rooms[1]),otherId=await person(admin,'가상 다른 학생','student',rooms[0]),parentId=await person(admin,'가상 보호자','parent');await admin.req('admin/families','POST',{parentId,studentId});
 const parent=await claim(admin,parentId,'parent'),student=await claim(admin,studentId,'student'),other=await claim(admin,otherId,'other');
 // A connected bridge can still hold a directory that predates these people.
 // Each publisher appears only after its own fresh directory and teacher proof have arrived.
 await wait(async()=>(await a.req('external-announcements/setup')).teacherId===aPortal&&(await b.req('external-announcements/setup')).teacherId===bPortal);
 const mobileA=await claim(admin,aPortal,'mobilea'),mobileB=await claim(admin,bPortal,'mobileb');
 await new Client(office).req('timetable/day', 'GET',undefined,401);await a.req('timetable/import','POST',file('base.xlsx','base'),403);await a.req('admin/timetable-managers','POST',{userId:a.user.id,enabled:true},403);await owner.req('timetable/preview','POST',{},400,false);check('authentication, CSRF and dedicated manager permissions enforced');
 await owner.req('admin/timetable-managers','POST',{userId:a.user.id,enabled:true});assert.equal((await a.req('timetable/setup')).canManage,true);
 const imported=await a.req('timetable/import','POST',file('base.xlsx','base'));check('authorized manager uploads synthetic school workbook');
 const mappings={classes:rooms.map((room,n)=>({source:`1학년 ${n+1}반`,id:room})),teachers:[{source:'가상 교사 A',id:a.user.id},{source:'가상 교사 B',id:b.user.id}]};
 const request={draftId:imported.draftId,start:'2026-08-01',end:'2027-02-28',...mappings};
 await a.req('timetable/preview','POST',request,409);for(const room of rooms)await owner.req('admin/timetable-homerooms','POST',{classId:room,teacherId:home.user.id});check('publishing requires explicit active homeroom mapping');
 await b.req('timetable/preview','POST',request,403);await a.req('timetable/preview','POST',{...request,teachers:[]},400);await a.req('timetable/preview','POST',{...request,classes:[null]},400);await a.req('timetable/preview','POST',{...request,classes:mappings.classes.map(c=>({...c,id:id()}))},400);check('missing, null and unknown teacher/class mappings rejected');
 const preview=await a.req('timetable/preview','POST',request);assert.equal((await a.req('timetable/day?date=2026-10-08')).revision,0);check('preview does not change live timetable');
 const commit={candidateId:preview.candidateId,clientId:id()},baseline=await a.req('timetable/publish','POST',commit);assert.equal((await a.req('timetable/publish','POST',commit)).id,baseline.id);check('confirmed publication is idempotent');
 await wait(async()=>(await student.req('timetable/day?date=2026-10-08')).revision===baseline.revision);check('outbound bridge delivers baseline to external app server');
 const before=await parent.req('timetable/day?date=2026-10-08');assert.equal(before.slots.length,12);assert.ok(before.slots.every(s=>s.classId===rooms[1]&&s.source==='base'));await parent.req('timetable/day?date=2026-10-08&classId='+rooms[0],'GET',undefined,404);await student.req('timetable/day?mine=true','GET',undefined,404);check('student and parent can view only current authorized classes');
 const importedDaily=await a.req('timetable/import','POST',file('daily.xlsx','daily'));assert.equal(importedDaily.workbook.date,'2026-10-08');const dailyPreview=await a.req('timetable/preview','POST',{...request,draftId:importedDaily.draftId});assert.equal(dailyPreview.changedCount,3);const daily=await a.req('timetable/publish','POST',{candidateId:dailyPreview.candidateId,clientId:id()});check('dated preview detects exactly three changes');
 await wait(async()=>(await parent.req('timetable/day?date=2026-10-08')).revision===daily.revision);const changed=await parent.req('timetable/day?date=2026-10-08');assert.equal(changed.slots.filter(s=>s.changed).length,1);assert.equal(changed.slots.find(s=>s.period===2).teacherId,b.user.id);assert.equal(changed.slots.find(s=>s.period===7).subject,'');assert.ok((await parent.req('timetable/day?date=2026-10-09')).slots.every(s=>s.source==='base'));check('dated day overrides baseline including blank periods; other dates retain baseline');
 assert.equal((await mobileB.req('timetable/day?date=2026-10-08&mine=true')).slots.length,3);assert.ok((await mobileA.req('timetable/day?date=2026-10-08&mine=true')).slots.every(s=>s.teacherId===a.user.id));check('teacher personal timetable is derived from assigned teacher account');
 for(const recipient of [a,b,home,mobileA,mobileB,parent,student])assert.equal((await recipient.req('timetable/notices')).filter(n=>n.revision===daily.revision).length,1);assert.equal((await other.req('timetable/notices')).filter(n=>n.revision===daily.revision).length,0);check('old/new teachers, homeroom, student and guardian receive deduplicated durable notices');
 await parent.req('timetable/notices/'+daily.revision+'/read','POST');assert.ok((await parent.req('timetable/notices')).find(n=>n.revision===daily.revision).readAt);check('notice read receipt saved per recipient');
 const stale=await a.req('timetable/preview','POST',{...request,draftId:importedDaily.draftId});const partialImport=await a.req('timetable/import','POST',file('partial.xlsx','daily')),partialPreview=await a.req('timetable/preview','POST',{...request,draftId:partialImport.draftId});const partial=await a.req('timetable/publish','POST',{candidateId:partialPreview.candidateId,clientId:id()});await a.req('timetable/publish','POST',{candidateId:stale.candidateId,clientId:id()},409);check('stale preview cannot overwrite an intervening publication');
 await a.req('timetable/'+daily.id+'/cancel','POST',{candidateId:'',clientId:id()},409);await a.req('timetable/'+partial.id+'/cancel','POST',{candidateId:'',clientId:id()});const classOne=await a.req('timetable/day?date=2026-10-08&classId='+rooms[0]);assert.ok(classOne.slots.every(s=>s.source==='base'));assert.ok((await a.req('timetable/day?date=2026-10-08&classId='+rooms[1])).slots.every(s=>s.source==='daily'));check('cancelling partial dated publication restores only included class; previous daily version stays cancelled');
 const malformed=await a.req('timetable/day?date=2026-10-08');await a.req('timetable/import','POST',file('formula.xlsx','base'),400);await a.req('timetable/import','POST',file('external.xlsx','base'),400);assert.equal((await a.req('timetable/day?date=2026-10-08')).revision,malformed.revision);check('unsafe workbook imports leave current publication unchanged');
 const emptyImport=await a.req('timetable/import','POST',file('empty.xlsx','daily')),emptyPreview=await a.req('timetable/preview','POST',{...request,draftId:emptyImport.draftId});await stop(p);const empty=await a.req('timetable/publish','POST',{candidateId:emptyPreview.candidateId,clientId:id()});assert.equal((await a.req('timetable/day?date=2026-10-08')).slots.filter(s=>s.subject.length>0).length,0);await stop(o);startPortal();startOffice();await wait(async()=>(await fetch(office+'/health')).ok);await owner.login();await parent.login('parent');await wait(async()=>(await parent.req('timetable/day?date=2026-10-08')).revision===empty.revision);check('queued delivery survives both service restarts and preserves empty dated day');
 const unauth=await fetch(portal+'/bridge/timetable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});assert.equal(unauth.status,401);const bad=await fetch(portal+'/bridge/timetable',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({batch:{...empty,cells:[null]},homerooms:[],notices:[]})});assert.equal(bad.status,400);check('replica bridge requires service credential and validates null payloads');
 await admin.login();await admin.req('admin/families/'+parentId+'/'+studentId,'DELETE');await parent.req('timetable/day?date=2026-10-08','GET',undefined,401);await parent.login('parent');assert.equal((await parent.req('timetable/day?date=2026-10-08')).slots.length,0);assert.equal((await parent.req('timetable/notices')).length,0);check('guardian relationship removal revokes both schedule and notification access');
 await owner.req('admin/timetable-managers','POST',{userId:a.user.id,enabled:false});await a.login('teachera');await a.req('timetable/import','POST',file('daily.xlsx','daily'),403);check('manager grant removal takes effect on every new mutation');
 mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/timetable-checks.json',JSON.stringify({passed,source:'synthetic fixtures',version:'1.0.0'},null,2));console.log('Timetable service integration: '+passed.length+' checks passed.');
}finally{await stop(o);await stop(p);}
